UART_BAUD = 115200  # 设置 TI-MaixCAM2 通信波特率。
UART_DEVICE = "/dev/ttyS2"  # 设置 MaixCAM2 UART2 对应串口设备路径。
UART_TX_PIN = "B0"  # 设置 MaixCAM2 B0 引脚为 UART2 TX。
UART_RX_PIN = "B1"  # 设置 MaixCAM2 B1 引脚为 UART2 RX。
UART_TX_FUNC = "UART2_TX"  # 设置 B0 引脚复用为 UART2_TX。
UART_RX_FUNC = "UART2_RX"  # 设置 B1 引脚复用为 UART2_RX。
TRACK_PERIOD_MS = 20  # 设置 TRACK 输出目标周期，20ms 约等于 50Hz。
STATUS_PERIOD_MS = 1500  # 设置 STATUS 低频输出周期。
CAMERA_FPS = 60  # 设置双光斑检测相机目标帧率，实际以板端能力为准。
DEBUG_RENDER_EVERY = 5  # 设置板端调试画面每几帧刷新一次。
TRACK_3CM_PIXEL = 10  # 暂时把 10 像素等效为题面 3cm，后续现场只调这个像素参数。
TRACK_3CM_MM = 30  # 设置题面 3cm 对应的毫米值，用于把像素距离临时换算成 dist_mm。
TRACK_IMG_W = 640  # 设置双光斑检测输入图像宽度。
TRACK_IMG_H = 480  # 设置双光斑检测输入图像高度。
SPOT_IMG_W = TRACK_IMG_W  # 兼容原样复用的红点检测模块图像宽度字段。
SPOT_IMG_H = TRACK_IMG_H  # 兼容原样复用的红点检测模块图像高度字段。
RED_THRESHOLDS = [[45, 100, 8, 45, -20, 20]]  # 沿用红色工程粉红高亮激光外环 LAB 阈值。
GREEN_THRESHOLDS = [[40, 100, -70, -8, -20, 45]]  # 设置绿色高亮激光外环 LAB 起步阈值，现场按实拍继续收紧。
ROI_SIZE = 180  # 设置锁定后围绕上一帧光斑搜索的 ROI 边长。
LOST_TO_FULL = 4  # 设置 ROI 连续丢失多少帧后退回全屏搜索。
MIN_PIXELS = 3  # 设置 find_blobs 有效颜色像素下限。
MIN_AREA = 4  # 设置候选框面积下限。
MAX_AREA = 1600  # 设置候选框面积上限。
MAX_SIDE = 50  # 设置候选框最大边长。
MAX_RATIO10 = 30  # 设置宽高比上限乘以十，30 表示最大 3.0。
DEBUG_TEXT_SCALE = 2  # 设置调试文字放大倍数。
DEBUG_TEXT_STEP = 24  # 设置调试文字两行之间的垂直间隔。
CENTER_BOX_HALF = 3  # 设置光斑中心调试框半边长。
CORE_ROI_PAD = 6  # 设置亮芯定位时在颜色候选框外扩的像素边距。
CORE_ROI_MAX_SIDE = 5  # 限制亮芯搜索框最大边长，避免误检大候选时拖慢 50Hz 坐标流。
CORE_MIN_R = 190  # 设置红点白芯像素红通道最低值，用于排除普通灰白纸面。
CORE_MIN_G = 135  # 设置红点白芯像素绿通道最低值，用于确认中心足够亮。
CORE_MIN_B = 135  # 设置红点白芯像素蓝通道最低值，用于确认中心接近泛白高亮。
CORE_MIN_BRIGHT = 500  # 设置红点白芯像素 RGB 总亮度最低值。
CORE_MIN_RED_DELTA = 4  # 设置红通道相对绿或蓝的最低偏红量，用于排除纯白背景反光。
GREEN_CORE_MIN_R = 135  # 设置绿点亮芯像素红通道最低值，用于确认中心足够亮。
GREEN_CORE_MIN_G = 190  # 设置绿点亮芯像素绿通道最低值，用于排除普通灰白纸面。
GREEN_CORE_MIN_B = 135  # 设置绿点亮芯像素蓝通道最低值，用于确认中心接近泛白高亮。
GREEN_CORE_MIN_BRIGHT = 500  # 设置绿点亮芯像素 RGB 总亮度最低值。
GREEN_CORE_MIN_GREEN_DELTA = 4  # 设置绿通道相对红或蓝的最低偏绿量，用于排除纯白背景反光。
