UART_BAUD = 115200  # 设置 TI-MaixCAM2 通信波特率。
UART_DEVICE = "/dev/ttyS2"  # 设置 MaixCAM2 UART2 对应串口设备路径。
UART_TX_PIN = "B0"  # 设置 MaixCAM2 B0 引脚为 UART2 TX。
UART_RX_PIN = "B1"  # 设置 MaixCAM2 B1 引脚为 UART2 RX。
UART_TX_FUNC = "UART2_TX"  # 设置 B0 引脚复用为 UART2_TX。
UART_RX_FUNC = "UART2_RX"  # 设置 B1 引脚复用为 UART2_RX。
TRACK_PERIOD_MS = 20  # 设置 TRACK 输出目标周期，20ms 约等于 50Hz。
STATUS_PERIOD_MS = 1500  # 设置 STATUS 低频输出周期。
CAMERA_FPS = 60  # 设置双光斑检测相机目标帧率，实际以板端能力为准。
CAMERA_PROBE_ENABLE = False  # 关闭相机输入探针，恢复默认运行时不读取额外相机参数。
CAMERA_LOCK_INPUT = False  # 关闭相机输入锁定，保持原本自动曝光、自动增益和自动白平衡配置。
CAMERA_MANUAL_EXPOSURE_US = 0  # 恢复默认曝光控制，0 表示不写手动曝光。
CAMERA_MANUAL_GAIN = 0  # 恢复默认增益控制，0 表示不写手动增益。
CAMERA_MANUAL_ISO = 0  # 恢复默认 ISO 控制，0 表示不写手动 ISO。
CAMERA_MANUAL_WB_GAIN = []  # 恢复默认白平衡控制，空列表表示不写手动白平衡增益。
CAMERA_LUMA = -1  # 恢复默认亮度控制，-1 表示不改动。
CAMERA_CONTRAST = -1  # 恢复默认对比度控制，-1 表示不改动。
CAMERA_SATURATION = -1  # 恢复默认饱和度控制，-1 表示不改动。
CAMERA_SKIP_FRAMES_AFTER_CONFIG = 0  # 恢复默认启动流程，不额外丢弃配置稳定帧。
DEBUG_RENDER_EVERY = 5  # 设置板端调试画面每几帧刷新一次。
TRACK_3CM_PIXEL = 10  # 暂时把 10 像素等效为题面 3cm，后续现场只调这个像素参数。
TRACK_3CM_MM = 30  # 设置题面 3cm 对应的毫米值，用于把像素距离临时换算成 dist_mm。
RED_ONLY_TEST = False  # 关闭红点单跑验证模式，恢复红绿双光斑同时识别以开始调试绿点。
TRACK_IMG_W = 640  # 设置双光斑检测输入图像宽度。
TRACK_IMG_H = 480  # 设置双光斑检测输入图像高度。
SPOT_IMG_W = TRACK_IMG_W  # 兼容原样复用的红点检测模块图像宽度字段。
SPOT_IMG_H = TRACK_IMG_H  # 兼容原样复用的红点检测模块图像高度字段。
RED_THRESHOLDS = [[45, 100, 14, 64, -20, 20]]  # 使用当前 MaixCAM2 实测红色激光 LAB 阈值，放宽 A 通道下限以覆盖黑框内弱红。
GREEN_THRESHOLDS = [[60, 100, -63, -39, -22, 15]]  # 使用当前实拍标定得到的绿色激光 LAB 阈值。
ROI_SIZE = 180  # 设置锁定后围绕上一帧光斑搜索的 ROI 边长。
LOST_TO_FULL = 4  # 设置 ROI 连续丢失多少帧后退回全屏搜索。
MIN_PIXELS = 3  # 设置 find_blobs 有效颜色像素下限。
MIN_AREA = 4  # 设置候选框面积下限。
MAX_AREA = 1600  # 设置候选框面积上限。
MAX_SIDE = 50  # 设置候选框最大边长。
MAX_RATIO10 = 30  # 设置宽高比上限乘以十，30 表示最大 3.0。
MERGE_BLOB_DIST = 26  # 设置红点碎块合并距离，处理黑框边缘把激光红晕切成多块的情况。
GREEN_MERGE_BLOB_DIST = 24  # 设置绿点碎块合并距离，处理黑框边缘把绿色光晕切成多块的情况。
GREEN_MIN_DENSITY = 8  # 设置绿点候选最低填充率百分比，过滤黑框边缘稀疏噪声。
GREEN_FULL_MIN_ADV = 8  # 设置全屏捕获时绿点候选最低绿色优势，避免白色反光抢首次锁定。
GREEN_LOCK_MIN_ADV = 3  # 设置 ROI 锁定时绿点候选最低绿色优势，允许黑框内弱绿点继续跟踪。
GREEN_JUMP_ACCEPT_ADV = 22  # 设置绿点突跳候选最低绿色优势，避免黑框远端反光突然接管坐标。
GREEN_JUMP_ACCEPT_CORE = 1  # 设置绿点突跳候选最低亮芯命中数，没有亮芯时优先保持上一帧附近目标。
GREEN_GROUP_BONUS = 8  # 设置绿点多碎块合并后的单块奖励，防止黑框切裂光斑被单碎块压过。
GREEN_ADV_SAMPLE_GRID = 3  # 降低绿点候选绿色优势采样网格，减少每帧 get_pixel 开销。
DEBUG_TEXT_SCALE = 1  # 设置调试文字为 1 倍大小，减少遮挡并避免文字挤压。
DEBUG_TEXT_STEP = 13  # 设置收紧后的调试文字行距，匹配 1 倍字体高度。
DEBUG_DRAW_DETAIL = False  # 关闭 ROI、候选框和亮芯框细节绘制，减少现场观察干扰。
DEBUG_RGB_PROBE = False  # 关闭临时 RGB/sum/red_delta 探针，避免拖慢双光斑坐标流。
CENTER_BOX_HALF = 3  # 设置光斑中心调试框半边长。
RED_PROBE_RADIUS = 2  # 设置红点候选红色优势十字采样半径。
RED_ADV_MIN = 10  # 设置红点最低红色优势，r - max(g, b) 小于该值只不给加分。
RED_ADV_STRONG = 55  # 设置红点红色优势满分参考值，用于候选评分。
RED_ADV_SCORE_MAX = 35  # 设置红点红色优势最多给候选增加的分数。
GREEN_PROBE_RADIUS = 2  # 设置绿点候选绿色优势十字采样半径。
GREEN_ADV_MIN = 10  # 设置绿点最低绿色优势，g - max(r, b) 小于该值只不给加分。
GREEN_ADV_STRONG = 55  # 设置绿点绿色优势满分参考值，用于候选评分。
GREEN_ADV_SCORE_MAX = 35  # 设置绿点绿色优势最多给候选增加的分数。
LOCK_MAX_STEP = 8  # 设置锁定后单帧正常最大位移，超过时先尝试本地重捕获。
LOCAL_RECAPTURE_RADIUS = 6  # 设置突跳时围绕上一帧位置做本地颜色重捕获的半径。
LOCAL_RECAPTURE_MIN_ADV = 12  # 设置本地重捕获像素最低颜色优势。
LOCAL_RECAPTURE_MIN_PIXELS = 2  # 设置本地重捕获至少需要的颜色优势像素数量。
HOLD_LAST_MAX_LOST = 1  # 设置无候选时最多保持上一帧坐标的帧数。
CORE_ROI_PAD = 6  # 设置亮芯定位时在颜色候选框外扩的像素边距。
CORE_ROI_MAX_SIDE = 6  # 将亮芯搜索框上限降到 6 像素，优先恢复帧率并减少 get_pixel 扫描开销。
GREEN_CORE_ROI_MAX_SIDE = 6  # 限制绿点亮芯搜索框边长，避免低帧率同时覆盖绿色外圈中心。
CORE_PEAK_MARGIN = 28  # 设置亮芯峰值聚类亮度容差，只取最亮峰值附近的小簇参与中心计算。
CORE_CLUSTER_RADIUS = 4  # 设置亮芯峰值聚类半径，避免黑框边缘大片泛红区域拉偏中心。
CORE_SCORE_RED_GAIN = 2  # 设置亮芯峰值评分中红色优势的权重，防止普通白色反光抢占峰值。
CORE_MIN_R = 190  # 设置红点白芯像素红通道最低值，用于排除普通灰白纸面。
CORE_MIN_G = 135  # 设置红点白芯像素绿通道最低值，用于确认中心足够亮。
CORE_MIN_B = 135  # 设置红点白芯像素蓝通道最低值，用于确认中心接近泛白高亮。
CORE_MIN_BRIGHT = 500  # 设置红点白芯像素 RGB 总亮度最低值。
CORE_MIN_RED_DELTA = 4  # 设置红通道相对绿或蓝的最低偏红量，用于排除纯白背景反光。
GREEN_CORE_SCORE_GREEN_GAIN = 2  # 设置绿点亮芯评分中的绿色优势权重，优先选择真正带绿光晕的高亮点。
GREEN_CORE_PEAK_MARGIN = 28  # 设置绿点亮芯峰值聚类亮度容差，只聚合最亮中心附近的小簇。
GREEN_CORE_CLUSTER_RADIUS = 4  # 设置绿点亮芯峰值聚类半径，避免外部光圈把中心拉偏。
GREEN_CORE_MIN_R = 120  # 降低绿点亮芯红通道最低值，兼容夜晚自动曝光下偏绿的激光中心。
GREEN_CORE_MIN_G = 180  # 降低绿点亮芯绿通道最低值，保留夜晚弱亮芯捕获能力。
GREEN_CORE_MIN_B = 95  # 降低绿点亮芯蓝通道最低值，避免绿色激光中心偏黄绿时被漏掉。
GREEN_CORE_MIN_BRIGHT = 440  # 降低绿点亮芯 RGB 总亮度门槛，适配当前夜晚画面。
GREEN_CORE_MIN_GREEN_DELTA = 4  # 设置绿通道相对红或蓝的最低偏绿量，用于排除纯白背景反光。
