UART_BAUD = 115200  # 设置 TI-MaixCAM 通信波特率。
UART_DEVICE = "/dev/ttyS1"  # 设置 MaixCAM-Pro 18/19 引脚对应 UART1 设备路径。
UART_TX_PIN = "A19"  # 设置 MaixCAM-Pro 19 号引脚为 UART1 TX。
UART_RX_PIN = "A18"  # 设置 MaixCAM-Pro 18 号引脚为 UART1 RX。
UART_TX_FUNC = "UART1_TX"  # 设置 19 号引脚复用为 UART1_TX。
UART_RX_FUNC = "UART1_RX"  # 设置 18 号引脚复用为 UART1_RX。
SPOT_PERIOD_MS = 20  # 设置 SPOT 输出目标周期，20ms 约等于 50Hz。
STATUS_PERIOD_MS = 1500  # 设置 STATUS 低频输出周期。
CAMERA_FPS = 60  # 设置红点检测相机目标帧率，实际以板端能力为准。
DEBUG_RENDER_EVERY = 5  # 设置板端调试画面每几帧刷新一次。
A4_LOCKED_RESEND_MS = 100  # 设置 A4_LOCKED 未确认时的重发间隔。
A4_LOCKED_MAX_RETRY = 5  # 设置 A4_LOCKED 最大重发次数。
SPOT_IMG_W = 640  # 设置红点检测输入图像宽度。
SPOT_IMG_H = 480  # 设置红点检测输入图像高度。
RED_THRESHOLDS = [[45, 100, 8, 45, -20, 20]]  # 设置粉红高亮激光外环 LAB 起步阈值，现场按实拍继续收紧。
ROI_SIZE = 180  # 设置锁定后围绕上一帧红点搜索的 ROI 边长。
LOST_TO_FULL = 4  # 设置 ROI 连续丢失多少帧后退回全屏搜索。
MIN_PIXELS = 3  # 设置 find_blobs 有效红色像素下限。
MIN_AREA = 4  # 设置候选框面积下限。
MAX_AREA = 1600  # 设置候选框面积上限。
MAX_SIDE = 50  # 设置候选框最大边长。
MAX_RATIO10 = 30  # 设置宽高比上限乘以十，30 表示最大 3.0。
DEBUG_TEXT_SCALE = 2  # 设置调试文字放大倍数。
DEBUG_TEXT_STEP = 24  # 设置调试文字两行之间的垂直间隔。
CENTER_BOX_HALF = 3  # 设置红点中心调试框半边长。
CORE_ROI_PAD = 6  # 设置白芯定位时在红色候选框外扩的像素边距。
CORE_ROI_MAX_SIDE = 5  # 限制白芯搜索框最大边长，避免误检大候选时拖慢 50Hz 坐标流。
CORE_MIN_R = 190  # 设置白芯像素红通道最低值，用于排除普通灰白纸面。
CORE_MIN_G = 135  # 设置白芯像素绿通道最低值，用于确认中心确实足够亮。
CORE_MIN_B = 135  # 设置白芯像素蓝通道最低值，用于确认中心接近泛白高亮。
CORE_MIN_BRIGHT = 500  # 设置白芯像素 RGB 总亮度最低值，用于压掉暗粉色外圈。
CORE_MIN_RED_DELTA = 4  # 设置红通道相对绿或蓝的最低偏红量，用于排除纯白背景反光。
A4_IMG_W = 640  # 设置 A4 黑框测试版检测处理图像和协议输出宽度。
A4_IMG_H = 480  # 设置 A4 黑框测试版检测处理图像和协议输出高度。
A4_BLACK_MAX_GRAY = 100  # 设置黑胶带灰度阈值，低于该值认为是黑色候选。
A4_MORPH_KERNEL = 3  # 设置黑色二值图形态学核大小，用于连接胶带断点并去除小噪声。
A4_POLY_EPS1000 = 25  # 设置轮廓四边形拟合精度，25 表示周长的 2.5%。
A4_EDGE_POINT_MAX_DIST = 6  # 设置边线精修时轮廓点到粗边的最大距离，单位为 640x480 坐标像素。
A4_EDGE_MIN_POINTS = 6  # 设置每条边参与直线拟合的最少轮廓点数。
A4_REFINE_SHIFT_MAX = 20  # 设置精修角点相对粗角点的最大允许位移，防止噪声把边线拉飞。
A4_OUTER_LINE_OFFSET_PX = 0  # 设置外框四条边沿远离中心方向外移的像素补偿。
A4_OUTER_AREA_MIN = 3200  # 设置 A4 外框最小面积，过滤远处噪声和铅笔淡线。
A4_OUTER_AREA_MAX = 280000  # 设置 A4 外框最大面积，避免整屏阴影或贴边大块误检。
A4_ASPECT_MIN10 = 11  # 设置 A4 外接矩形最小长宽比乘以十。
A4_ASPECT_MAX10 = 18  # 设置 A4 外接矩形最大长宽比乘以十。
A4_HOLE_RATIO_MIN100 = 35  # 设置内孔面积占外框面积的最小百分比。
A4_HOLE_RATIO_MAX100 = 92  # 设置内孔面积占外框面积的最大百分比。
A4_HOLE_RATIO_TARGET100 = 72  # 设置 A4 胶带环内孔面积占比参考值，用于置信度评分。
A4_STABLE_FRAMES = 4  # 设置连续稳定多少帧后允许 LOCK_A4 锁存。
A4_STABLE_SHIFT_MAX = 10  # 设置稳定判定中角点最大允许位移像素。
A4_STABLE_ANGLE10_MAX = 30  # 设置稳定判定中角度最大允许变化，单位为 0.1 度。
A4_POINT_BOX_HALF = 2  # 设置 A4 overlay 角点小方框半边长。
