id: red_vision
name: Red Vision
name[zh]: 红色视觉
version: 0.1.0
icon: ''
author: 23e
desc: Red laser spot and A4 target vision app.
desc[zh]: 红色激光点和 A4 靶纸视觉模块。
files:
  - app.yaml
  - config.py
  - main.py
  - protocol.py
  - vision_a4.py  # 打包 A4 黑胶带闭合框检测模块。
  - vision_spot.py
